### ISSUE TITLE
style attributes are not correctly set

### ISSUE THREAD

**Issue by Hammster** [zaceno/hyperlit#2]
Using style attributes will result in errors since the properties on `el.style[propertyName]` are set via index property setter which are not supported on the `style` property.

## Example

```js
const increase = (state) => {
  return { ...state, count: state.count + 1 }
}

const decrease = (state) => {
  return { ...state, count: state.count - 1 }
}


const counter = ({ count }) => html`
  <div class="window">
    <div class="title-bar">
      <div class="title-bar-text">
        Hyperapp counter
      </div>

      <div class="title-bar-controls">
        <button aria-label="Minimize"></button>
        <button aria-label="Maximize"></button>
        <button aria-label="Close"></button>
      </div>
    </div>
    <div class="window-body">
      <p>Count: ${count}</p>
      <section class="field-row" style="justify-content: flex-end">
        <button ${{ onclick: increase }}>+</button>
        <button ${{ onclick: decrease }}>-</button>
      </section>
    </div>
  </div>
```

**Comment by zaceno** [comment]
Thanks for reporting! I'm going to pass the buck to hyperapp on this though.  See `hyperlit` is really just an alternative to using `h` from hyperapp.   I'm not doing anything clever, but passing everything on to `h` (in the future I might start getting clever-er)

That means: 

```html
<section class="field-row" style="justify-content: flex-end">
  ...
</section>
```

is equivalent to calling:

```js
h('section', {
  class: 'field-row',
  style: 'justify-content: flex-end'
}, [....])
```

And hyperapp actually doesn't support using the style prop like that (because we are actually using the prop, not the attribute, desipite how it looks) is like this:

```
h({
h('section', {
  class: 'field-row',
  style: { justifyContent: 'flex-end' }
}, [....])})
```

In other words, your example should work like this: 

```html
<section class="field-row" style=${{justifyContent: 'flex-end}}>
...
</section>
```

Your assumption about the style prop is entirely reasonable. I've asked before to have style _optionally_ work like the style attribute does, i e with a string. (I actually think it did at some point). If you feel strongly about it, I suggest opening an issue at https://github.com/jorgebucaran/hyperapp

Also, your unfamiliarity with how hyperapp handles various things differently is entirely forgivable since there aren't (yet) any good docs online. They are coming afaik. If you want to read up on hyperapp more, I'd suggest the [tutorial](https://hyperapp.dev/tutorial) which I think is quite good (I wrote it, after all ;) ).
