### ISSUE TITLE
Why are we using .flat()?

### ISSUE THREAD

**Issue by jorgebucaran** [zaceno/hyperlit#6]
Why do we need to [flatten children](https://github.com/zaceno/hyperlit/blob/269aa79c692727a202d3c18df04ac16f5c6eab7e/babel-plugin-hyperlit/html.js#L4)? I'm sure this question will come up again and again, so it would be nice if there was an explanation we could refer to when we need to refresh our memory.

**Comment by zaceno** [comment]
For context, this is currently only something that needs to be handled by the function in `babel-plugin-hyperlit/html.js`, because when we are directly parsing hyperlit, the flattening occurs as part of the parsing process, but that is not possible in the context of a babel-plugin (this is part of the transformation we still need to shunt to the runtime context).

As for why it is needed, it is because we want to support injecting dynamic content into other content. Content is represented as arrays of vnodes. So we need to support arrays (=content) which can contain a mix of of vnodes and injected content (arrays).

As to how far deep we need to go, I'm not sure. Currently I'm using `.flat(2)` but it may be that simply `.flat()` would suffice. I found setting up tests for babel-plugins difficult, so I haven't been able to verify. But I surely will, eventually. Leaving this issue open until that question is resolved.

**Comment by zaceno** [comment]
Tried `.flat()` in babel-plugin-hyperlit@0.0.2 and it seems to work. So I'm going with that for now
