### ISSUE TITLE
whitespace between element and text node not preserved

### ISSUE THREAD

**Issue by kwasniew** [zaceno/hyperlit#9]
I'm porting RealWorldApp to hyperlit and noticed only one issue so far (being a drop-in replacement delivered on its promise :)).

Please check the corresponding test showing the gist of the discrepancy I found:
```js
test('whitespace between element and text preserved', t => {
    t.deepEqual(
        x`
            <div>
                <span>a</span> b
            </div>`,
        h('div', {}, [
            h('span', {}, ['a']),
            ' b'
        ])
    )
})
```
It looks like the space character before "b" is not preserved. I checked what htm is doing and it preserves any number of spaces before the text.

**Comment by zaceno** [comment]
Thanks @kwasniew for the kind words and the report. Going to look in to this right away.

**Comment by zaceno** [comment]
I'd like to ask: what's your feeling about how whitespace in general should be handled. I've been trying to remove all but the essential whitespace (although I missed this case, obviously). The easiest for me would be to leave all whitespace in – but that's not what htm does either. 

For instance, htm turns this:

```js
html`
  <div>
    <span>a</span>
    b
  </div>`
```

into this:

```js
h('div', {}, [
  h('span', {}, ['a']),
  'b',
])
```

whereas my initial naive attempt to solve your test makes that example result in:

```js
h('div', {}, [
  h('span', {}, ['a']),
  '    b', // <----- notice extra spaces
])
```

... so basically I'm playing whitespace-whack-a-mole. 😅 My question is: is that ok? Should I just leave all whitespace in? If not - what should be removed?

**Comment by zaceno** [comment]
@kwasniew earlier comments aside, this should be fixed and all tests passing in  v0.1.4 – give it a shot! 🎉 
Thanks again for bringing this to my attention!

**Comment by kwasniew** [comment]
Thanks for a fix. I've already switched RWA to the latest version and everything looks good :)
I've done a quick research looking for the whitespace handling rules in htm/JSX and the most approachable explanation I found is here: https://www.javascriptstuff.com/how-whitespace-works-in-jsx/. 
As you said just leaving the whitespaces and letting the browser do the collapsing is the easiest thing to do at the expense of creating extra text nodes. It would be interesting to see how it affects the https://github.com/krausest/js-framework-benchmark.

**Comment by zaceno** [comment]
@kwasniew thanks for finding that reference to how JSX handles whitespace! I’m mainly aiming for htm compatibility but presumably htm is doing the same because it is trying to be a replacement for JSX. I might just use that reference to set up some more whitespace tests and see what I can do.

As you know my aim is to be htm compatible - but that’s just the initial phase. Once I feel like hyperlit has got some more battle-testing, I’ll release it as 1.0 and then move on to 2.0 where I plan to drop some features in exchange for speed & smallness. At that point I will probably experiment a bit with leaving whitespace alone.
